# Generated by Django 5.0.6 on 2026-09-04 09:13

import submissions.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_name', models.CharField(help_text='Full name of the submitting student.', max_length=150, verbose_name='Student Name')),
                ('task_name', models.CharField(help_text='Title or name of the assigned task.', max_length=200, verbose_name='Task Name')),
                ('original_filename', models.CharField(help_text='Original name of the uploaded ZIP file.', max_length=255, verbose_name='Original Filename')),
                ('stored_filename', models.CharField(help_text='Unique server-side filename.', max_length=255, verbose_name='Stored Filename')),
                ('file', models.FileField(help_text='Original ZIP file preserved on server storage.', upload_to=submissions.validators.generate_secure_storage_path, validators=[submissions.validators.validate_zip_file_security], verbose_name='ZIP File')),
                ('file_size', models.PositiveBigIntegerField(help_text='Size of the uploaded file in bytes.', verbose_name='File Size (Bytes)')),
                ('status', models.CharField(choices=[('Pending', 'Pending'), ('Reviewed', 'Reviewed')], db_index=True, default='Pending', max_length=20, verbose_name='Status')),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Submitted At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Updated At')),
            ],
            options={
                'verbose_name': 'Student Submission',
                'verbose_name_plural': 'Student Submissions',
                'ordering': ['-submitted_at'],
                'indexes': [models.Index(fields=['status'], name='idx_submission_status'), models.Index(fields=['submitted_at'], name='idx_submission_submitted_at'), models.Index(fields=['student_name'], name='idx_submission_student_name'), models.Index(fields=['task_name'], name='idx_submission_task_name')],
            },
        ),
    ]
