# Generated by Django 5.0.6 on 2026-09-04 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='google_drive_error',
            field=models.TextField(blank=True, null=True, verbose_name='Google Drive Error Log'),
        ),
        migrations.AddField(
            model_name='submission',
            name='google_drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Google Drive File ID'),
        ),
        migrations.AddField(
            model_name='submission',
            name='google_drive_status',
            field=models.CharField(choices=[('Not Uploaded', 'Not Uploaded'), ('Uploaded', 'Uploaded'), ('Failed', 'Failed')], db_index=True, default='Not Uploaded', max_length=20, verbose_name='Google Drive Status'),
        ),
        migrations.AddField(
            model_name='submission',
            name='google_drive_uploaded_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Google Drive Uploaded At'),
        ),
        migrations.AddField(
            model_name='submission',
            name='google_drive_url',
            field=models.URLField(blank=True, max_length=500, null=True, verbose_name='Google Drive URL'),
        ),
        migrations.AddField(
            model_name='submission',
            name='sha256_checksum',
            field=models.CharField(blank=True, db_index=True, help_text='Hexadecimal SHA-256 hash of original ZIP file for binary integrity verification.', max_length=64, null=True, verbose_name='SHA-256 Checksum'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['google_drive_status'], name='idx_sub_gdrive_status'),
        ),
        migrations.AddIndex(
            model_name='submission',
            index=models.Index(fields=['sha256_checksum'], name='idx_sub_sha256'),
        ),
    ]
