# Generated by Django 5.0.6 on 2026-09-04 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('submissions', '0002_submission_google_drive_error_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleOAuthCredential',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_token_data', models.TextField(help_text='AES-encrypted JSON payload containing Google OAuth refresh token and client metadata.', verbose_name='Encrypted Token Data')),
                ('user_email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Authorized User Email')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Connected At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Updated At')),
            ],
            options={
                'verbose_name': 'Google OAuth Credential',
                'verbose_name_plural': 'Google OAuth Credentials',
                'ordering': ['-updated_at'],
            },
        ),
    ]
